# Generated by Django 5.2.5 on 2025-11-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_delete_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Category',
            new_name='category',
        ),
    ]
